# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [4]:
from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

print(model_linear.coef_)


[[-9.76990521e-02  4.46100994e-02  2.66968740e-02  1.56664261e+00
  -1.51996941e+01  3.97704392e+00  3.85175436e-03 -1.38262949e+00
   2.74477870e-01 -1.15841416e-02 -9.87172913e-01  1.00781041e-02
  -5.61028166e-01]]


In [5]:
y_pred = model_linear.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [6]:
print("R^2: {}".format(model_linear.score(X_test, y_test)))
print("R^2: {}".format(model_linear.score(X_train, y_train)))

R^2: 0.6082310210323043
R^2: 0.7635733388804014


## 4. Calculate and print mean squared error for both the training and the testing set.

In [7]:
from sklearn.metrics import mean_squared_error

In [8]:
rmse = mean_squared_error(y_test, y_pred)
print('Root Mean Squared Error: {}'.format(rmse))

Root Mean Squared Error: 26.81367055980713


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [9]:
from sklearn.metrics import mean_absolute_error

In [10]:
rmae = mean_absolute_error(y_test, y_pred)
print('Root Mean Absolute Error: {}'.format(rmae))

Root Mean Absolute Error: 3.1827109454975733


## Classification Model Evaluation

In [39]:
from sklearn.datasets import load_iris

data_i = load_iris()

X = pd.DataFrame(data_i["data"], columns=data_i["feature_names"])
y = pd.DataFrame(data_i["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [28]:
y.value_counts()

class
2        50
1        50
0        50
dtype: int64

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [17]:
from sklearn.linear_model import LogisticRegression

model_logistic = LogisticRegression(solver="lbfgs")
model_logistic.fit(X_train, y_train)
print(model_logistic.coef_)

y_pred = model_logistic.predict(X_test)

[[-0.46220302  0.82745634 -2.37900069 -0.97236086]
 [ 0.53645975 -0.29264585 -0.20363879 -0.82218789]
 [-0.07425673 -0.53481049  2.58263948  1.79454875]]


/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [18]:
from sklearn.metrics import accuracy_score
print("Accuracy",accuracy_score(y_test, y_pred))

Accuracy 0.9666666666666667


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [19]:
from sklearn.metrics import balanced_accuracy_score
print("Balanced Accuracy",balanced_accuracy_score(y_test, y_pred))

Balanced Accuracy 0.9761904761904763


## 10. Calculate and print the precision score for both the training and the testing set.

In [31]:
from sklearn.metrics import precision_score
print("Precision",precision_score(y_test, y_pred, average="weighted"))

Precision 0.9700000000000001


## 11. Calculate and print the recall score for both the training and the testing set.

In [32]:
from sklearn.metrics import recall_score
print("Recall",recall_score(y_test, y_pred, average="weighted"))

Recall 0.9666666666666667


## 12. Calculate and print the F1 score for both the training and the testing set.

In [33]:
from sklearn.metrics import f1_score
print("F1 Score",f1_score(y_test, y_pred, average="weighted"))

F1 Score 0.9669265756985055


## 13. Generate confusion matrices for both the training and the testing set.

In [34]:
from sklearn.metrics import confusion_matrix

In [43]:
names = data_i["target_names"]

In [45]:
pd.DataFrame(confusion_matrix(y_test, y_pred), columns=names, index=names)

setosa  versicolor  virginica
setosa           7           0          0
versicolor       0          13          1
virginica        0           0          9

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.