# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [47]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

In [48]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [50]:
from sklearn.linear_model import LinearRegression

model_linear = LinearRegression()
model_linear.fit(X_train, y_train)

print(model_linear.coef_)


[[-9.92718673e-02  4.70090746e-02  1.56906887e-02  2.89437014e+00
  -1.46489266e+01  3.56859069e+00 -1.56575696e-03 -1.43522622e+00
   3.41511449e-01 -1.64698112e-02 -9.89048566e-01  7.89843444e-03
  -5.41207346e-01]]


In [51]:
y_pred = model_linear.predict(X_test)
y_pred_train = model_linear.predict(X_train)

## 3. Calculate and print R-squared for both the training and the testing set.

In [52]:
print("R^2: {}".format(model_linear.score(X_test, y_test)))
print("R^2: {}".format(model_linear.score(X_train, y_train)))

R^2: 0.7335357267424067
R^2: 0.7394883893388112


## 4. Calculate and print mean squared error for both the training and the testing set.

In [53]:
from sklearn.metrics import mean_squared_error

In [54]:
rmse = mean_squared_error(y_test, y_pred)
rmse_2 = mean_squared_error(y_train, y_pred_train)
print('Root Mean Squared Error (test): {}'.format(rmse))
print('Root Mean Squared Error (train): {}'.format(rmse_2))

Root Mean Squared Error (test): 18.897300245171333
Root Mean Squared Error (train): 22.859306002089436


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [9]:
from sklearn.metrics import mean_absolute_error

In [56]:
rmae = mean_absolute_error(y_test, y_pred)
rmae_2 = mean_absolute_error(y_train, y_pred_train)
print('Root Mean Absolute Error (test): {}'.format(rmae))
print('Root Mean Absolute Error (train): {}'.format(rmae_2))

Root Mean Absolute Error (test): 3.094071566068065
Root Mean Absolute Error (train): 3.3636589212493617


## Classification Model Evaluation

In [58]:
from sklearn.datasets import load_iris

data_i = load_iris()

X = pd.DataFrame(data_i["data"], columns=data_i["feature_names"])
y = pd.DataFrame(data_i["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [59]:
y.value_counts()

class
2        50
1        50
0        50
dtype: int64

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [61]:
from sklearn.linear_model import LogisticRegression

model_logistic = LogisticRegression(solver="lbfgs")
model_logistic.fit(X_train, y_train)
print(model_logistic.coef_)

y_pred = model_logistic.predict(X_test)
y_pred_train = model_logistic.predict(X_train)

[[-0.40788034  0.9254422  -2.39929995 -1.01946916]
 [ 0.29751204 -0.30759481 -0.23150935 -0.78052548]
 [ 0.11036831 -0.61784739  2.6308093   1.79999464]]


/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/usr/local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [62]:
from sklearn.metrics import accuracy_score
print("Accuracy (test)",accuracy_score(y_test, y_pred))
print("Accuracy (train)",accuracy_score(y_train, y_pred_train))

Accuracy (test) 0.9
Accuracy (train) 0.9916666666666667


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [63]:
from sklearn.metrics import balanced_accuracy_score
print("Balanced Accuracy (test)",balanced_accuracy_score(y_test, y_pred))
print("Balanced Accuracy (train)",balanced_accuracy_score(y_train, y_pred_train))

Balanced Accuracy (test) 0.8968253968253969
Balanced Accuracy (train) 0.9912280701754387


## 10. Calculate and print the precision score for both the training and the testing set.

In [65]:
from sklearn.metrics import precision_score
print("Precision (test)",precision_score(y_test, y_pred, average="weighted"))
print("Precision (train)",precision_score(y_train, y_pred_train, average="weighted"))

Precision (test) 0.9053030303030302
Precision (train) 0.9918560606060607


## 11. Calculate and print the recall score for both the training and the testing set.

In [66]:
from sklearn.metrics import recall_score
print("Recall (test)",recall_score(y_test, y_pred, average="weighted"))
print("Recall (train)",recall_score(y_train, y_pred_train, average="weighted"))

Recall (test) 0.9
Recall (train) 0.9916666666666667


## 12. Calculate and print the F1 score for both the training and the testing set.

In [67]:
from sklearn.metrics import f1_score
print("F1 Score (test)",f1_score(y_test, y_pred, average="weighted"))
print("F1 Score (train)",f1_score(y_train, y_pred_train, average="weighted"))

F1 Score (test) 0.901159420289855
F1 Score (train) 0.9916590038314176


## 13. Generate confusion matrices for both the training and the testing set.

In [68]:
from sklearn.metrics import confusion_matrix

In [69]:
names = data_i["target_names"]

In [70]:
pd.DataFrame(confusion_matrix(y_test, y_pred), columns=names, index=names)

setosa  versicolor  virginica
setosa          11           0          0
versicolor       0          10          2
virginica        0           1          6

In [71]:
pd.DataFrame(confusion_matrix(y_train, y_pred_train), columns=names, index=names)

setosa  versicolor  virginica
setosa          39           0          0
versicolor       0          37          1
virginica        0           0         43

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.